Repository GSG-G9/MASA-Store, pull requests merged in 2021-02, with the labels that each got.

#7 create inital file structure
  .eslintrc.js
  .gitignore
  .vscode/settings.json
  README.md
  __test__/index.test.js
  client/.env
  client/.gitignore
  client/package-lock.json
  client/package.json
  client/public/favicon.ico
  client/public/index.html
  client/public/logo192.png
  client/public/logo512.png
  client/public/manifest.json
  client/public/robots.txt
  client/src/App.js
  client/src/assets/.gitkeep
  client/src/component/component1/index.js
  client/src/component/component1/style.css
  client/src/component/index.js
  client/src/index.css
  client/src/index.js
  client/src/pages/page1/index.js
  client/src/pages/page1/style.css
  client/src/setupTests.js
  client/src/utilities/index.js
  package-lock.json
  package.json
  server/app.js
  server/controllers/buyer/index.js
  server/controllers/common/index.js
  server/controllers/errors/index.js
  server/controllers/index.js
  server/controllers/seller/index.js
  server/database/connection.js
  server/database/data/build.js
  server/database/data/bulid.sql
  server/database/data/fakeData.sql
  server/database/quieres/index.js
  server/index.js
  server/middlewares/index.js
  server/routes/index.js
  server/utilities/index.js
Labels: in progress

#37 Adding Fake Data
  package.json
  server/database/data/build.sql
  server/database/data/fakeData.sql
Labels: awaiting review

#42 Get /clients Route
  __test__/getClients.test.js
  package.json
  server/controllers/index.js
  server/controllers/seller/getClientsHandler.js
  server/controllers/seller/index.js
  server/database/quieres/getClients.js
  server/database/quieres/index.js
  server/routes/index.js
  server/routes/seller.js
Labels: awaiting review

#41 get all products data
  __test__/getAllProducts.test.js
  __test__/getClients.test.js
  server/controllers/common/allProductsHandler.js
  server/controllers/common/index.js
  server/controllers/seller/getClientsHandler.js
  server/database/data/fakeData.sql
  server/database/queries/getAllProducts.js
  server/database/queries/getClients.js
  server/database/queries/index.js
  server/routes/common.js
  server/routes/index.js
Labels: awaiting review

#43 Get /orders Route
  __test__/getorders.test.js
  server/controllers/index.js
  server/controllers/seller/getOrdersHandler.js
  server/controllers/seller/index.js
  server/database/queries/getOrders.js
  server/database/queries/index.js
  server/routes/error.js
  server/routes/seller.js
Labels: awaiting review

#45 16 get product by
  __test__/getProductById.test.js
  client/package.json
  package.json
  server/app.js
  server/controllers/common/index.js
  server/controllers/common/productByIdHandler.js
  server/database/connection.js
  server/database/queries/getProductById.js
  server/database/queries/index.js
  server/routes/common.js
Labels: awaiting review

#52 sign-up route
  .eslintrc.js
  __test__/signUp.test.js
  package.json
  server/controllers/common/index.js
  server/controllers/common/signUpHandler.js
  server/controllers/index.js
  server/database/data/fakeData.sql
  server/database/queries/getClientDataByEmail.js
  server/database/queries/index.js
  server/database/queries/signUp.js
  server/routes/common.js
  server/routes/index.js
  server/utilities/Validation /signUp.js
  server/utilities/createToken.js
  server/utilities/index.js
Labels: awaiting review

#50 18 20 Get Product By Top-rating Trending
  __test__/getProductsByTopRating.test.js
  __test__/getProductsByTrending.test.js
  server/controllers/common/index.js
  server/controllers/common/productsByTopRatingHandler.js
  server/controllers/common/productsByTrendingHandler.js
  server/database/queries/getProductsByTopRating.js
  server/database/queries/getProductsByTrending.js
  server/database/queries/index.js
  server/routes/common.js
Labels: awaiting review

#53 30 route get cart
  __test__/getCartProducts.test.js
  server/controllers/buyer/getCartHandler.js
  server/controllers/buyer/index.js
  server/controllers/index.js
  server/database/queries/getCartProducts.js
  server/database/queries/index.js
  server/routes/buyer.js
Labels: awaiting review

#55 31 POST /cart Route
  __test__/addCartProduct.test.js
  server/controllers/buyer/addCartProductHandler.js
  server/controllers/buyer/index.js
  server/controllers/index.js
  server/database/queries/addCartProduct.js
  server/database/queries/checkCartProduct.js
  server/database/queries/index.js
  server/routes/buyer.js
Labels: awaiting review

#56 27 Delete /cart Route
  __test__/deleteFromCart.test.js
  server/controllers/buyer/deleteFromCartHandler.js
  server/controllers/buyer/index.js
  server/controllers/index.js
  server/database/queries/deleteFromCart.js
  server/database/queries/index.js
  server/routes/buyer.js
Labels: awaiting review

#57 14-13 get profile data, and update profile data
  __test__/getProfileUSerById.test.js
  __test__/putProfileDataById.test.js
  server/controllers/buyer/getProfileUSerById.js
  server/controllers/buyer/index.js
  server/controllers/buyer/putProfileDataById.js
  server/controllers/index.js
  server/database/queries/getProfileUser.js
  server/database/queries/index.js
  server/database/queries/putProfileUser.js
  server/routes/buyer.js
Labels: awaiting review

#62 11 add product
  __test__/addProduct.test.js
  package.json
  server/controllers/index.js
  server/controllers/seller/addProductHandler.js
  server/controllers/seller/index.js
  server/database/queries/addImg.js
  server/database/queries/addProduct.js
  server/database/queries/index.js
  server/routes/seller.js
  server/utilities/Validation /addProductValidation.js
  server/utilities/index.js
Labels: awaiting review

#51 GET products/:Category & /product-search ?category=value
  __test__/getProductsByCatogory.test.js
  __test__/productSearchBycategoryHandler.test.js
  server/controllers/common/index.js
  server/controllers/common/productSearchCategoryHandler.js
  server/controllers/common/productsByCategoryHandler.js
  server/database/queries/getProductsByCategory.js
  server/database/queries/index.js
  server/routes/common.js
Labels: awaiting review

#61 15 delete product seller
  __test__/deleteProduct.test.js
  server/controllers/index.js
  server/controllers/seller/deleteProductHandler.js
  server/controllers/seller/index.js
  server/database/data/build.sql
  server/database/queries/deleteProduct.js
  server/database/queries/index.js
  server/routes/seller.js
Labels: awaiting review

#58 28 Put /cart Route
  __test__/updateCart.test.js
  server/controllers/buyer/index.js
  server/controllers/buyer/updateCartHandler.js
  server/controllers/index.js
  server/database/queries/index.js
  server/database/queries/updateCart.js
  server/routes/buyer.js
Labels: awaiting review

#63 12 update product
  __test__/putProduct.test.js
  server/controllers/index.js
  server/controllers/seller/index.js
  server/controllers/seller/putProductHandler.js
  server/database/queries/index.js
  server/database/queries/putProduct.js
  server/routes/seller.js
Labels: awaiting review

#65 33 Get /search?section=value for seller
  __test__/sellerSearch.test.js
  server/controllers/index.js
  server/controllers/seller/index.js
  server/controllers/seller/searchHandler.js
  server/database/queries/getClients.js
  server/database/queries/getOrders.js
  server/routes/seller.js
Labels: awaiting review

#64 creating the log out route
  .vscode/settings.json
  package-lock.json
  server/controllers/buyer/index.js
  server/controllers/buyer/signoutHandler.js
  server/controllers/index.js
  server/routes/buyer.js
Labels: awaiting review

#99 72 configure rtl support, 85 Configuration of Theme Provider for Material-UI
  client/package-lock.json
  client/package.json
  client/public/index.html
  client/src/App.js
  client/src/component/theme/globals.js
  client/src/component/theme/theme.js
  client/src/index.css
Labels: awaiting review

#98 FRONT-END ESling Config
  client/.env
  client/.eslintrc
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/component/theme/globals.js
  client/src/component/theme/theme.js
  client/src/index.js
Labels: awaiting review

#59 create route and query for getting user order by id
  __test__/addUserOrdersById.test.js
  __test__/getUserOrders.test.js
  server/controllers/buyer/addUserOrdersById.js
  server/controllers/buyer/getOrdersByUsersId.js
  server/controllers/buyer/index.js
  server/controllers/errors/handleServerError.js
  server/controllers/index.js
  server/database/data/build.sql
  server/database/queries/addOrdersByUsersId.js
  server/database/queries/getOrdersByUsersId.js
  server/database/queries/getUsersOrdersByProductId.js
  server/database/queries/index.js
  server/database/queries/placeOrder.js
  server/database/queries/updateProductById.js
  server/database/queries/updateUserFinancialStatement.js
  server/routes/buyer.js
  server/utilities/Validation /addOrderValidation.js
  server/utilities/index.js
Labels: awaiting review

#103 86 front end input field
  client/.eslintrc
  client/package-lock.json
  client/package.json
  client/src/component/InputField/index.js
  client/src/component/index.js
Labels: awaiting review

#102 101 is Auth route
  server/controllers/buyer/index.js
  server/controllers/buyer/isAuth.js
  server/controllers/index.js
  server/database/queries/getStarterData.js
  server/middleware/isAuthorized.js
  server/routes/buyer.js
Labels: awaiting review

#106 footer component
  client/package-lock.json
  client/package.json
  client/public/index.html
  client/src/assets/logo.svg
  client/src/component/Footer/index.js
  client/src/component/Footer/style.css
  client/src/component/component1/index.js
  client/src/component/component1/style.css
  client/src/component/index.js
  client/src/component/theme/theme.js
Labels: awaiting review

#110 78 product card component
  .vscode/settings.json
  client/src/App.js
  client/src/component/ProductCard/index.js
  client/src/component/index.js
Labels: awaiting review

#112 create button and validation as a prop-type
  client/src/component/ButtonComponent/index.js
  client/src/component/ButtonComponent/style.css
  client/src/component/index.js
Labels: awaiting review

#113 90 notif card
  client/package-lock.json
  client/package.json
  client/src/component/NotificationCard/index.js
  client/src/component/index.js
  client/src/utilities/timeDifference.js
Labels: Change request

#100 91-React Router
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/component/Footer/index.js
  client/src/component/Header/index.js
  client/src/index.js
  client/src/pages/Admin/AddProductsAdminPage/index.js
  client/src/pages/Admin/AdminHomePage/index.js
  client/src/pages/Admin/ClientsPage/index.js
  client/src/pages/Admin/EditProductsAdminPage/index.js
  client/src/pages/Admin/OrdersPage/index.js
  client/src/pages/Admin/ProductsAdminPage/index.js
  client/src/pages/Common/404/index.js
  client/src/pages/Common/CategoryProductPage/index.js
  client/src/pages/Common/HomePage/index.js
  client/src/pages/Common/ProductDetailsPage/index.js
  client/src/pages/Common/SignInPage/index.js
  client/src/pages/Common/SignUpPage/index.js
  client/src/pages/User/CartPage/index.js
  client/src/pages/User/FavoritePage/index.js
  client/src/pages/User/OrderPage/index.js
  client/src/pages/User/ProfilePage/index.js
  client/src/pages/User/paymentPage/index.js
  client/src/pages/index.js
  client/src/pages/page1/index.js
  client/src/pages/page1/style.css
Labels: awaiting review, frontend

#111 create cart
  client/src/assets/watch.jpg
  client/src/component/Card/index.js
  client/src/component/index.js
  server/database/queries/getOrdersByUsersId.js
Labels: in progress

#114 73 front end header
  client/package-lock.json
  client/src/App.js
  client/src/component/Header/index.js
  client/src/component/Header/style.css
  client/src/component/theme/theme.js
  client/src/pages/Admin/AddProductsAdminPage/index.js
  client/src/pages/Admin/AdminHomePage/index.js
  client/src/pages/Admin/ClientsPage/index.js
  client/src/pages/Admin/EditProductsAdminPage/index.js
  client/src/pages/Admin/OrdersPage/index.js
  client/src/pages/Admin/ProductsAdminPage/index.js
  client/src/pages/Common/404/index.js
  client/src/pages/Common/CategoryProductPage/index.js
  client/src/pages/Common/HomePage/index.js
  client/src/pages/Common/ProductDetailsPage/index.js
  client/src/pages/Common/SearchPage/index.js
  client/src/pages/Common/SignInPage/index.js
  client/src/pages/User/CartPage/index.js
  client/src/pages/User/FavoritePage/index.js
  client/src/pages/User/OrderPage/index.js
  client/src/pages/User/ProfilePage/index.js
  client/src/pages/User/paymentPage/index.js
  client/src/pages/index.js
Labels: awaiting review

#116 sign up page
  client/src/pages/Common/SignInPage/index.js
  client/src/pages/Common/SignUpPage/index.js
  server/database/queries/getStarterData.js
Labels: awaiting review

#117 Products pages
  client/.eslintrc
  client/package-lock.json
  client/package.json
  client/public/index.html
  client/src/App.js
  client/src/component/CardContainer/CardContainer.css
  client/src/component/CardContainer/index.js
  client/src/component/ProductCard/index.js
  client/src/component/index.js
  client/src/pages/Common/CategoryProductPage/index.js
  client/src/pages/Common/HomePage/index.js
  client/src/pages/Common/SearchPage/index.js
  client/src/utilities/dataFormatter.js
  package-lock.json
  package.json
Labels: awaiting review

#124 create 404 page
  client/src/pages/Common/404/index.js
Labels: awaiting review

#126 update header
  client/.eslintignore
  client/src/App.js
  client/src/component/CardContainer/CardContainer.css
  client/src/component/Header/index.js
  client/src/pages/Common/CategoryProductPage/index.js
  client/src/pages/Common/HomePage/index.js
  server/controllers/buyer/isAuth.js
  server/routes/index.js
Labels: in progress

#128 Favorite page
  client/src/pages/Common/CategoryProductPage/index.js
  client/src/pages/Common/HomePage/index.js
  client/src/pages/Common/ProductDetailsPage/index.js
  client/src/pages/Common/ProductDetailsPage/productPage.css
  client/src/pages/User/FavoritePage/index.js
  client/src/utilities/dataFormatter.js
Labels: frontend, in progress

#123 payment page
  client/src/component/CardContainer/CardContainer.css
  client/src/component/ProductCard/index.js
  client/src/pages/User/paymentPage/AddressForm.js
  client/src/pages/User/paymentPage/PaymentForm.js
  client/src/pages/User/paymentPage/Review.js
  client/src/pages/User/paymentPage/index.js
Labels: awaiting review
